import type { MayaPageGuide } from '@/features/maya/content/types'

/**
 * Guias por rota real do escritório (`/app/firm/...`).
 * O mais específico (search + prefix maior) ganha em `resolveMayaPage`.
 */
export const MAYA_PAGES: MayaPageGuide[] = [
  {
    id: 'dashboard',
    pathPrefix: '/app/firm/dashboard',
    exact: true,
    where: 'Painel do escritório',
    summary:
      'Aqui vê o estado da carteira de um relance: o que falta configurar, prazos próximos, documentos e o próximo passo recomendado.',
    audience: 'Toda a equipa do escritório',
    goal: 'Saber por onde começar o dia e o que precisa de atenção.',
    firstTimeHint:
      'Se acabou de chegar, siga o cartão «Próximo passo» — normalmente começa pelo logótipo, pela página pública e pelo primeiro serviço publicado.',
    topicIds: ['tour', 'public-page', 'service', 'clients', 'dashboard-kpis'],
    primaryIntentId: 'tour',
  },
  {
    id: 'irs',
    pathPrefix: '/app/firm/irs',
    exact: true,
    where: 'área de IRS',
    summary:
      'Aqui configura os serviços de apoio ao IRS que o escritório oferece aos clientes, define o que precisa de recolher e publica um formulário na página pública. O Teglion não calcula o imposto — ajuda a captar pedidos e a organizar a informação.',
    audience: 'Equipa que prepara a campanha de IRS e recebe os pedidos',
    goal: 'Ter pelo menos um serviço IRS publicado e receber pedidos em Solicitações.',
    firstTimeHint:
      'Se é a primeira vez, comece por activar o Modelo 3 (à esquerda) ou por «Criar serviço». Depois abra Editar para publicar na página pública.',
    emptyHint:
      'Ainda não há serviço IRS. Active um modelo pronto ou crie um serviço — só depois de publicar é que os clientes o vêem.',
    topicIds: [
      'irs',
      'irs-create-service',
      'irs-modelo3',
      'irs-form-questions',
      'irs-anexos',
      'irs-publish',
      'irs-send',
      'irs-track',
      'irs-edit',
      'irs-problems',
    ],
    primaryIntentId: 'irs-campaign',
  },
  {
    id: 'services-inquiries',
    pathPrefix: '/app/firm/services',
    search: { key: 'tab', value: 'inquiries' },
    where: 'Solicitações',
    summary:
      'Aqui chegam os pedidos de pessoas que preencheram um serviço na página pública — ainda não são clientes da carteira. Contacte, peça documentos e avance o estado.',
    audience: 'Quem trata de novos contactos e captação',
    goal: 'Não deixar pedidos da página pública por ver.',
    emptyHint:
      'Ainda não há solicitações. Publique um serviço na página pública e partilhe o link — os pedidos aparecem aqui, não na Central.',
    topicIds: ['requests', 'service', 'public-page', 'irs-track'],
    primaryIntentId: 'requests',
  },
  {
    id: 'services-central',
    pathPrefix: '/app/firm/services',
    search: { key: 'tab', value: 'central' },
    where: 'Central de Serviços',
    summary:
      'Aqui ficam os pedidos de clientes que já estão na carteira e usam a app Teglion. A captação pública (novos contactos) fica em Solicitações.',
    audience: 'Equipa que trabalha com clientes já activos',
    goal: 'Acompanhar pedidos internos da carteira, separados dos da página pública.',
    topicIds: ['requests-central', 'clients', 'service'],
    primaryIntentId: 'requests',
  },
  {
    id: 'services',
    pathPrefix: '/app/firm/services',
    where: 'Catálogo de Serviços',
    summary:
      'Aqui define o que o escritório oferece: active um modelo, crie um serviço, configure o formulário e publique-o na página pública. IRS tem uma área própria.',
    audience: 'Quem configura a oferta do escritório',
    goal: 'Ter serviços publicados para receber pedidos.',
    firstTimeHint: 'Active um modelo ou clique em adicionar serviço. Guardar ainda não publica — isso faz-se no passo Publicação.',
    emptyHint: 'Ainda não tem serviços. Adicione o primeiro e, quando estiver pronto, publique-o com um endereço (slug).',
    topicIds: [
      'service',
      'service-editor',
      'service-form',
      'service-publish',
      'requests',
      'irs-campaign',
    ],
    primaryIntentId: 'service',
  },
  {
    id: 'clients-create',
    pathPrefix: '/app/firm/clients',
    exact: true,
    search: { key: 'create', value: '1' },
    where: 'cadastro de um novo cliente',
    summary:
      'Vamos cadastrar um cliente. O assistente pede Identificação, Fiscal, Pessoa Singular se o tipo for Independente ou Particular, Responsáveis e Serviços. No último passo o botão é «Criar cliente».',
    audience: 'Quem está a adicionar um cliente à carteira',
    goal: 'Completar o cadastro e gravar. Depois a lista actualiza — a ficha não abre sozinha.',
    firstTimeHint:
      'Comece pelo tipo e pelo NIF. Valide o NIF antes de Continuar. Os campos mudam conforme Empresa, Independente ou Particular.',
    topicIds: [
      'clients-create',
      'clients-create-identification',
      'clients-create-fiscal',
      'clients-create-singular',
      'clients-create-owners',
      'clients-create-services',
      'clients-create-save',
      'clients-next-steps',
      'clients-problems',
    ],
    primaryIntentId: 'clients-create',
  },
  {
    id: 'clients-hub-profile',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'profile' },
    where: 'Perfil deste cliente',
    summary:
      'Está a editar os dados deste cliente. São os mesmos campos do cadastro, em edição inline: as alterações guardam automaticamente. Aqui também estão serviços contratados e notas internas.',
    audience: 'Quem corrige ou completa o cadastro desta empresa',
    goal: 'Actualizar dados, serviços associados e notas internas.',
    topicIds: [
      'client-profile',
      'client-services',
      'client-notes',
      'clients-invite',
      'client-hub',
      'clients-create',
    ],
    primaryIntentId: 'client-profile',
  },
  {
    id: 'clients-hub-accesses',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'accesses' },
    where: 'Acessos oficiais deste cliente',
    summary:
      'Está nas senhas dos portais oficiais desta empresa (AT, Segurança Social, ViaCTT, IAPMEI, Relatório Único). Guardar ou ver uma senha pede a sua palavra-passe do Teglion. O cliente no portal não vê este bloco.',
    audience: 'Equipa do escritório que trata desta empresa nos portais do Estado',
    goal: 'Gravar ou consultar um acesso oficial com confirmação de identidade.',
    firstTimeHint:
      'O olho não mostra a senha logo: confirma primeiro que é você. A senha visível desaparece ao fim de cerca de 30 segundos.',
    topicIds: ['client-official-accesses', 'client-hub', 'client-profile'],
    primaryIntentId: 'client-official-accesses',
  },
  {
    id: 'clients-hub-timeline',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'timeline' },
    where: 'Actividade deste cliente',
    summary:
      'Está no histórico deste cliente: o feed visível e o histórico completo. Ocultar tira o evento do feed sem apagar o registo.',
    audience: 'Quem acompanha o que aconteceu nesta empresa',
    goal: 'Ler, filtrar e limpar o feed de actividade.',
    topicIds: ['client-history', 'client-hub', 'client-actions'],
    primaryIntentId: 'client-history',
  },
  {
    id: 'clients-hub-obligations',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'obligations' },
    where: 'Obrigações deste cliente',
    summary:
      'Está nos prazos fiscais desta empresa. Esta tab lista; criar e tratar faz-se no módulo Obrigações, pelo botão «Abrir módulo completo».',
    audience: 'Quem acompanha prazos deste cliente',
    goal: 'Ver o que está pendente e abrir o módulo completo se precisar de agir.',
    emptyHint: 'Sem obrigações registadas para esta empresa. Abra o módulo completo para criar.',
    topicIds: ['client-obligations', 'obligations', 'client-hub'],
    primaryIntentId: 'client-obligations',
  },
  {
    id: 'clients-hub-documents',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'documents' },
    where: 'Documentos deste cliente',
    summary:
      'Está nos documentos deste cliente. Aqui vê pedidos activos. Não carrega ficheiros nesta tab — use «Abrir pedidos» para criar ou gerir pedidos.',
    audience: 'Quem precisa dos comprovativos desta empresa',
    goal: 'Ver o que foi pedido e abrir o módulo de pedidos para continuar.',
    emptyHint: 'Sem pedidos de documentos activos. Abra pedidos para criar o primeiro.',
    topicIds: ['client-documents', 'documents-requests', 'documents', 'client-hub'],
    primaryIntentId: 'client-documents',
  },
  {
    id: 'clients-hub-tasks',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'tasks' },
    where: 'Tarefas deste cliente',
    summary:
      'Está nas tarefas desta empresa. Esta tab lista; criar e concluir faz-se no módulo Tarefas.',
    audience: 'Quem executa trabalho operacional deste cliente',
    goal: 'Ver tarefas desta ficha e abrir o módulo completo para agir.',
    topicIds: ['client-tasks', 'tasks-manual', 'client-hub'],
    primaryIntentId: 'client-tasks',
  },
  {
    id: 'clients-hub-messages',
    pathPrefix: '/app/firm/clients/',
    search: { key: 'section', value: 'messages' },
    where: 'Comunicação deste cliente',
    summary:
      'Está na conversa com este cliente. Distinto das notas internas do Perfil, que só a equipa vê.',
    audience: 'Quem fala com este cliente no Teglion',
    goal: 'Ler e responder nesta ficha, ou abrir o módulo Mensagens.',
    topicIds: ['client-messages', 'messages', 'client-notes', 'clients-invite'],
    primaryIntentId: 'client-messages',
  },
  {
    id: 'clients-hub',
    pathPrefix: '/app/firm/clients/',
    where: 'ficha deste cliente',
    summary:
      'Esta é a ficha deste cliente: resumo, perfil, acessos oficiais, actividade, documentos, obrigações, tarefas e comunicação. Daqui também convida ou gere o acesso ao portal. Não é o portal do cliente.',
    audience: 'Quem trata deste cliente no dia-a-dia',
    goal: 'Ver o estado do cliente e agir sem saltar entre ecrãs.',
    firstTimeHint:
      'Comece pelo Resumo. Editar abre o Perfil. Documentos e Serviços não se gerem todos aqui — a Maya explica cada tab.',
    topicIds: [
      'client-hub',
      'client-hub-overview',
      'client-profile',
      'client-official-accesses',
      'client-documents',
      'client-services',
      'client-requests',
      'client-notes',
      'client-history',
      'client-actions',
      'clients-invite',
    ],
    primaryIntentId: 'client-hub',
  },
  {
    id: 'clients',
    pathPrefix: '/app/firm/clients',
    exact: true,
    where: 'lista de Clientes',
    summary:
      'Está na área de Clientes. Aqui fica a carteira do escritório: cadastrar, procurar, filtrar e abrir cada ficha. O botão «Novo cliente» abre o assistente neste ecrã. «Ficha CSV» exporta ou importa a carteira em texto (sem macros). Isto não é o portal do cliente.',
    audience: 'Toda a equipa que gere a carteira',
    goal: 'Ter os clientes registados e, quando fizer sentido, com acesso ao portal.',
    firstTimeHint:
      'Comece por «Novo cliente». Depois abra a ficha para documentos, serviços associados, obrigações e convite ao portal.',
    emptyHint: 'Ainda não cadastrou nenhum cliente. Clique em «Novo cliente» para criar o primeiro.',
    topicIds: [
      'clients',
      'clients-create',
      'clients-search',
      'clients-filters',
      'clients-list',
      'client-hub',
      'clients-invite',
      'clients-next-steps',
      'clients-problems',
    ],
    primaryIntentId: 'clients',
  },
  {
    id: 'documents-requests',
    pathPrefix: '/app/firm/documents/requests',
    where: 'Documentos → Pedidos',
    summary:
      'Aqui faz pedidos formais de documentos a um cliente. O cliente vê o pedido no portal e envia os ficheiros.',
    audience: 'Quem precisa de recolher comprovativos e declarações',
    goal: 'Pedir o que falta e acompanhar o que já chegou.',
    emptyHint: 'Escolha um cliente e crie o primeiro pedido. Sem cliente na carteira, comece em Clientes.',
    topicIds: ['documents', 'documents-requests', 'clients'],
    primaryIntentId: 'documents',
  },
  {
    id: 'documents-files',
    pathPrefix: '/app/firm/documents/files',
    where: 'Documentos → Ficheiros',
    summary:
      'Aqui vê os ficheiros já recebidos, organizados por cliente e período. Serve para consultar e gerir o que já está no escritório.',
    audience: 'Quem consulta o arquivo corrente',
    goal: 'Encontrar um ficheiro sem sair do hub de documentos.',
    topicIds: ['documents', 'documents-files', 'documents-history'],
    primaryIntentId: 'documents',
  },
  {
    id: 'documents-history',
    pathPrefix: '/app/firm/documents/history',
    where: 'Documentos → Histórico',
    summary:
      'Aqui está o histórico consolidado de submissões — o rasto do que foi pedido e entregue ao longo do tempo.',
    audience: 'Quem precisa de auditoria ou contexto antigo',
    goal: 'Reconstruir o que aconteceu com os documentos de um cliente.',
    topicIds: ['documents-history', 'documents', 'clients'],
    primaryIntentId: 'documents',
  },
  {
    id: 'documents',
    pathPrefix: '/app/firm/documents',
    where: 'hub de Documentos',
    summary:
      'Aqui centraliza a papelada dos clientes: pedidos formais, ficheiros por período e histórico.',
    audience: 'Equipa operacional',
    goal: 'Pedir, receber e consultar documentos sem dispersar por e-mail.',
    topicIds: ['documents', 'documents-requests', 'documents-files', 'documents-history'],
    primaryIntentId: 'documents',
  },
  {
    id: 'tasks-obligations',
    pathPrefix: '/app/firm/tasks/obligations',
    where: 'Obrigações dos Clientes',
    summary:
      'Aqui acompanham-se os prazos dos clientes (IVA, IRS, Segurança Social…). Não confundir com Tarefas, que são o trabalho interno da equipa.',
    audience: 'Quem controla entregas e prazos fiscais',
    goal: 'Não deixar obrigações em atraso.',
    topicIds: ['obligations', 'fiscal-calendar', 'tasks-manual', 'clients'],
    primaryIntentId: 'obligations',
  },
  {
    id: 'tasks-manual',
    pathPrefix: '/app/firm/tasks/manual',
    where: 'Tarefas',
    summary:
      'Aqui cria e organiza o trabalho interno da equipa — o que o escritório precisa de fazer, ligado ou não a uma obrigação.',
    audience: 'Equipa operacional',
    goal: 'Distribuir trabalho e não perder prazos internos.',
    topicIds: ['tasks-manual', 'obligations', 'clients'],
    primaryIntentId: 'obligations',
  },
  {
    id: 'tasks-calendar',
    pathPrefix: '/app/firm/tasks/calendar',
    where: 'calendário de operações',
    summary:
      'Aqui vê tarefas e prazos em vista de calendário, para planear a semana do escritório.',
    audience: 'Quem planeia a operação',
    goal: 'Ver o que cai em cada dia.',
    topicIds: ['tasks-manual', 'obligations', 'fiscal-calendar'],
    primaryIntentId: 'obligations',
  },
  {
    id: 'tasks-clients',
    pathPrefix: '/app/firm/tasks/clients',
    where: 'tarefas por cliente',
    summary:
      'Aqui o trabalho aparece agrupado por cliente, para ver quem tem mais pendências.',
    audience: 'Quem gere a carteira operacionalmente',
    goal: 'Priorizar clientes com mais trabalho em aberto.',
    topicIds: ['tasks-manual', 'clients', 'obligations'],
    primaryIntentId: 'obligations',
  },
  {
    id: 'tasks',
    pathPrefix: '/app/firm/tasks',
    where: 'Gestor de Operações',
    summary:
      'Aqui está o trabalho do escritório: resumo, obrigações dos clientes, tarefas internas, calendário e vista por cliente.',
    audience: 'Toda a equipa operacional',
    goal: 'Saber o que está em atraso e o que fazer a seguir.',
    firstTimeHint: 'Comece pelo Resumo. Obrigações = prazos dos clientes. Tarefas = trabalho interno.',
    topicIds: ['obligations', 'tasks-manual', 'fiscal-calendar'],
    primaryIntentId: 'obligations',
  },
  {
    id: 'agenda-settings',
    pathPrefix: '/app/firm/agenda',
    search: { key: 'panel', value: 'settings' },
    where: 'Definições da Agenda',
    summary:
      'Aqui define os horários em que o escritório aceita marcações, a duração dos intervalos, até quando se pode marcar, e a ligação ao Google Calendar.',
    audience: 'Quem configura o agendamento público',
    goal: 'Ter disponibilidade gravada para a página pública poder oferecer horários.',
    topicIds: ['booking', 'agenda', 'agenda-google', 'service'],
    primaryIntentId: 'booking',
  },
  {
    id: 'agenda',
    pathPrefix: '/app/firm/agenda',
    where: 'Agenda',
    summary:
      'Aqui marca reuniões com clientes, vê a semana ou o mês, e nas Definições configura a disponibilidade para agendamento na página pública.',
    audience: 'Quem agenda e atende',
    goal: 'Ter a agenda do escritório visível e, se quiser, marcações a chegar do site.',
    firstTimeHint: 'Crie um evento ou abra Definições para definir horários de marcação.',
    topicIds: ['agenda', 'booking', 'agenda-google', 'service'],
    primaryIntentId: 'agenda',
  },
  {
    id: 'fiscal-calendar',
    pathPrefix: '/app/firm/fiscal-calendar',
    where: 'Calendário fiscal',
    summary:
      'Aqui organiza prazos fiscais do escritório: pode importar o modelo Portugal, criar eventos e categorias, e definir recorrências.',
    audience: 'Quem alimenta os prazos nacionais',
    goal: 'Ter os prazos certos a alimentar as obrigações dos clientes.',
    topicIds: ['fiscal-calendar', 'obligations'],
    primaryIntentId: 'fiscal-calendar',
  },
  {
    id: 'messages',
    pathPrefix: '/app/firm/messages',
    where: 'Mensagens',
    summary:
      'Aqui conversa com os clientes da carteira: texto, anexos e histórico. O cliente lê no portal Teglion.',
    audience: 'Quem comunica com a carteira',
    goal: 'Manter a conversa no mesmo sítio, sem perder o rasto.',
    emptyHint: 'Seleccione um cliente na lista. Sem clientes, comece em Clientes.',
    topicIds: ['messages', 'documents', 'clients'],
    primaryIntentId: 'messages',
  },
  {
    id: 'alerts',
    pathPrefix: '/app/firm/alerts',
    where: 'Central de Alertas',
    summary:
      'Aqui envia comunicados curtos e rastreáveis a um, vários ou todos os clientes — prazos, avisos, novidades operacionais.',
    audience: 'Quem comunica avisos a toda a carteira',
    goal: 'Avisar com prova de leitura, sem usar a caixa de e-mail pessoal.',
    topicIds: ['alerts', 'news', 'clients'],
    primaryIntentId: 'alerts',
  },
  {
    id: 'news',
    pathPrefix: '/app/firm/news',
    where: 'Notícias',
    summary:
      'Aqui publica artigos para os clientes lerem no portal. É conteúdo mais longo do que um alerta pontual.',
    audience: 'Quem produz conteúdo informativo para a carteira',
    goal: 'Ter informação útil visível no portal dos clientes.',
    topicIds: ['news', 'alerts', 'clients'],
    primaryIntentId: 'news',
  },
  {
    id: 'settings-public',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'pagina-publica' },
    where: 'Definições → Página pública',
    summary:
      'Aqui edita o site público do escritório: link, destaque, secções, rodapé e publicação. Sem publicar, o site não fica visível na internet.',
    audience: 'Quem trata da presença pública do escritório',
    goal: 'Publicar o link teglion.com/o-seu-slug e partilhá-lo.',
    firstTimeHint:
      'Defina o link (slug) e o nome na barra, preencha o destaque, guarde o rascunho, pré-visualize e só depois publique.',
    topicIds: [
      'public-page',
      'public-page-sections',
      'public-page-publish',
      'service',
      'booking',
    ],
    primaryIntentId: 'public-page',
  },
  {
    id: 'settings-payments',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'pagamentos' },
    where: 'Definições → Pagamentos',
    summary:
      'Aqui o responsável do escritório liga a conta Stripe para os clientes pagarem serviços online. O dinheiro vai para a conta do escritório — a mensalidade Teglion é outra área (Plano).',
    audience: 'Responsável (dono) do escritório',
    goal: 'Deixar a conta Stripe pronta para receber nos serviços publicados.',
    topicIds: ['payments', 'billing', 'service'],
    primaryIntentId: 'payments',
  },
  {
    id: 'settings-team',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'equipa' },
    where: 'Definições → Equipa',
    summary:
      'Aqui gere quem trabalha no escritório: convidar por e-mail, criar membros, departamentos e permissões.',
    audience: 'Quem administra acessos da equipa',
    goal: 'Cada pessoa ter a conta certa, sem partilhar passwords.',
    topicIds: ['settings-team', 'settings', 'settings-profile'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-profile',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'perfil' },
    where: 'Definições → O seu perfil',
    summary:
      'Aqui gere a sua conta pessoal no Teglion (nome, e-mail, palavra-passe) — não os dados do escritório.',
    audience: 'Cada utilizador da equipa',
    goal: 'Manter os seus dados de acesso correctos.',
    topicIds: ['settings-profile', 'settings'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-firm',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'escritorio' },
    where: 'Definições → Escritório',
    summary:
      'Aqui estão o nome, contactos e dados fiscais do escritório — a identidade legal e de contacto da firma.',
    audience: 'Quem pode editar dados do escritório',
    goal: 'Ter nome e contactos certos no produto e na página pública.',
    topicIds: ['settings-firm', 'settings', 'public-page'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-identity',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'identidade' },
    where: 'Definições → Identidade',
    summary:
      'Aqui define o logótipo e o aspeto visual do escritório no menu e no portal dos clientes.',
    audience: 'Quem trata da imagem do escritório',
    goal: 'O escritório ser reconhecível dentro do Teglion e no portal.',
    firstTimeHint: 'Carregar o logótipo é normalmente o primeiro passo do painel.',
    topicIds: ['settings-identity', 'public-page', 'settings'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-tags',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'etiquetas' },
    where: 'Definições → Etiquetas',
    summary:
      'Aqui cria etiquetas para classificar clientes e outros registos do escritório.',
    audience: 'Quem organiza a carteira',
    goal: 'Filtrar e agrupar clientes com etiquetas consistentes.',
    topicIds: ['settings-tags', 'clients'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-notifications',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'notificacoes' },
    where: 'Definições → Notificações',
    summary:
      'Aqui escolhe que avisos o escritório quer receber sobre a operação no Teglion.',
    audience: 'Equipa do escritório',
    goal: 'Receber o essencial, sem ruído.',
    topicIds: ['settings-notifications', 'settings'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings-help',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'ajuda' },
    where: 'Ajuda e suporte',
    summary:
      'Aqui encontra os canais oficiais para falar com uma pessoa da AfDigital — WhatsApp, e-mail ou telefone.',
    audience: 'Qualquer utilizador do escritório',
    goal: 'Pedir ajuda humana quando a Maya não chega.',
    topicIds: ['human-support', 'tour'],
    primaryIntentId: 'human-support',
  },
  {
    id: 'settings-about',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'sobre' },
    where: 'Sobre o Teglion',
    summary:
      'Aqui está a apresentação do produto Teglion, desenvolvido e operado pela AfDigital — Soluções Tecnológicas.',
    audience: 'Qualquer utilizador',
    goal: 'Saber o que é o produto e quem o opera.',
    topicIds: ['tour', 'human-support'],
    primaryIntentId: 'tour',
  },
  {
    id: 'settings-close',
    pathPrefix: '/app/firm/settings',
    search: { key: 'tab', value: 'encerrar' },
    where: 'Encerrar conta',
    summary:
      'Aqui o responsável pode encerrar a conta do escritório. Esta acção é irreversível e só aparece a quem tem permissão para tal.',
    audience: 'Responsável do escritório',
    goal: 'Só usar se realmente pretende encerrar o escritório no Teglion.',
    topicIds: ['settings-close', 'billing', 'human-support'],
    primaryIntentId: 'settings',
  },
  {
    id: 'settings',
    pathPrefix: '/app/firm/settings',
    where: 'Definições',
    summary:
      'Aqui configura a identidade, a página pública, os dados do escritório, pagamentos, o seu perfil, a equipa e as notificações. Escolha a secção no menu.',
    audience: 'Equipa do escritório (algumas secções só o responsável)',
    goal: 'Deixar o escritório identificável e a página pública pronta.',
    topicIds: [
      'settings',
      'settings-identity',
      'public-page',
      'settings-firm',
      'payments',
      'settings-team',
      'settings-profile',
    ],
    primaryIntentId: 'settings',
  },
  {
    id: 'billing',
    pathPrefix: '/app/firm/billing',
    where: 'Plano e subscrição',
    summary:
      'Aqui gere o plano Teglion do escritório (teste, mensal ou anual). Isto é a mensalidade da plataforma — não os pagamentos que os seus clientes lhe fazem.',
    audience: 'Responsável do escritório',
    goal: 'Manter o acesso ao Teglion activo.',
    topicIds: ['billing', 'payments', 'tour'],
    primaryIntentId: 'billing',
  },
  {
    id: 'help',
    pathPrefix: '/app/firm/ajuda',
    where: 'Ajuda e suporte',
    summary:
      'Canais oficiais para falar com uma pessoa da AfDigital. Eu, Maya, ajudo a usar o Teglion; o suporte humano trata de casos que precisam de uma pessoa.',
    audience: 'Qualquer utilizador do escritório',
    goal: 'Contactar suporte quando precisar.',
    topicIds: ['human-support', 'tour'],
    primaryIntentId: 'human-support',
  },
  {
    id: 'about',
    pathPrefix: '/app/firm/sobre',
    where: 'Sobre o Teglion',
    summary:
      'O Teglion é o produto SaaS para escritórios; a AfDigital — Soluções Tecnológicas é quem o desenvolve e opera.',
    audience: 'Qualquer utilizador',
    goal: 'Perceber a identidade do produto.',
    topicIds: ['tour', 'human-support'],
    primaryIntentId: 'tour',
  },
  {
    id: 'portal-home',
    pathPrefix: '/app/client',
    exact: true,
    where: 'Início do portal',
    summary:
      'Aqui vê o próximo passo com o escritório, um resumo do que precisa de atenção, e os serviços que pode pedir.',
    audience: 'Cliente do escritório',
    goal: 'Saber o que fazer agora, sem caçar datas.',
    firstTimeHint: 'Se for a primeira visita, comece pelo cartão «Próximo passo» ou pergunte à Maya.',
    topicIds: ['portal-home', 'portal-requests', 'portal-services', 'portal-maya'],
    primaryIntentId: 'portal-home',
  },
  {
    id: 'portal-requests',
    pathPrefix: '/app/client/requests',
    where: 'Pedidos',
    summary: 'Documentos e informações que o escritório lhe pediu. Entregue aqui — fica registado.',
    audience: 'Cliente do escritório',
    goal: 'Não deixar pedidos pendentes.',
    emptyHint: 'Sem pedidos neste momento. Quando o escritório precisar de algo, aparece aqui.',
    topicIds: ['portal-requests', 'portal-documents', 'portal-messages'],
    primaryIntentId: 'portal-requests',
  },
  {
    id: 'portal-services',
    pathPrefix: '/app/client/services',
    where: 'Serviços',
    summary: 'O que o seu escritório oferece. Pode agendar um horário ou pedir o serviço por mensagem.',
    audience: 'Cliente do escritório',
    goal: 'Encontrar e pedir o serviço certo.',
    emptyHint: 'O escritório ainda não publicou serviços neste portal. Use Mensagens.',
    topicIds: ['portal-services', 'portal-booking', 'portal-messages'],
    primaryIntentId: 'portal-services',
  },
  {
    id: 'portal-messages',
    pathPrefix: '/app/client/messages',
    where: 'Mensagens',
    summary: 'Conversa com a equipa do escritório. Texto e ficheiros ficam neste histórico.',
    audience: 'Cliente do escritório',
    goal: 'Falar com o escritório sem espalhar o assunto.',
    topicIds: ['portal-messages', 'portal-firm-contact'],
    primaryIntentId: 'portal-messages',
  },
  {
    id: 'portal-documents',
    pathPrefix: '/app/client/documents',
    where: 'Documentos',
    summary: 'Envie comprovativos e veja o que o escritório lhe enviou.',
    audience: 'Cliente do escritório',
    goal: 'Entregar ficheiros no sítio certo.',
    topicIds: ['portal-documents', 'portal-requests'],
    primaryIntentId: 'portal-documents',
  },
  {
    id: 'portal-deadlines',
    pathPrefix: '/app/client/agenda',
    where: 'Prazos',
    summary: 'Obrigações agrupadas: em atraso, esta semana, mais tarde. Toque para o detalhe.',
    audience: 'Cliente do escritório',
    goal: 'Tratar primeiro o que está atrasado ou esta semana.',
    topicIds: ['portal-deadlines', 'portal-requests'],
    primaryIntentId: 'portal-deadlines',
  },
  {
    id: 'portal-more',
    pathPrefix: '/app/client/more',
    where: 'Mais',
    summary: 'Prazos, documentos, avisos e a sua conta. A Maya também explica cada um destes ecrãs.',
    audience: 'Cliente do escritório',
    goal: 'Chegar ao resto do portal sem sobrecarregar a barra principal.',
    topicIds: ['portal-home', 'portal-account', 'portal-deadlines'],
    primaryIntentId: 'portal-home',
  },
  {
    id: 'portal-account',
    pathPrefix: '/app/client/account',
    where: 'Conta e ajuda',
    summary: 'O seu perfil neste portal, notificações, instalar a app, e ajuda da Maya.',
    audience: 'Cliente do escritório',
    goal: 'Gerir a conta e pedir ajuda sem sair do portal.',
    topicIds: ['portal-account', 'portal-maya', 'portal-firm-contact'],
    primaryIntentId: 'portal-account',
  },
  {
    id: 'portal-updates',
    pathPrefix: '/app/client/updates',
    where: 'Avisos',
    summary: 'Alertas e notícias que o escritório publicou para si.',
    audience: 'Cliente do escritório',
    goal: 'Não perder um aviso importante.',
    topicIds: ['portal-home', 'portal-messages'],
    primaryIntentId: 'portal-home',
  },
  {
    id: 'landing-home',
    pathPrefix: '/',
    exact: true,
    where: 'página do Teglion',
    summary:
      'Aqui apresenta-se o Teglion: a plataforma para escritórios de contabilidade em Portugal. Eu explico o produto, o trial de 14 dias, a página pública, o portal do cliente — e se quiser uma pessoa, abro o WhatsApp da AfDigital.',
    audience: 'Quem está a conhecer o Teglion',
    goal: 'Perceber se o Teglion serve o escritório e começar o trial ou falar connosco.',
    firstTimeHint:
      'Se só tem um minuto: o Teglion organiza clientes, documentos, prazos e captação. Evoluímos o sistema todos os dias. Comece grátis 14 dias, ou fale com uma pessoa no WhatsApp.',
    topicIds: [
      'landing-what',
      'landing-daily',
      'landing-trial',
      'landing-page',
      'landing-portal',
      'landing-pricing',
      'landing-human',
    ],
    primaryIntentId: 'landing-what',
  },
]

export const MAYA_CLIENT_CATALOG_INTENT_IDS = [
  'portal-home',
  'portal-requests',
  'portal-services',
  'portal-booking',
  'portal-messages',
  'portal-documents',
  'portal-deadlines',
  'portal-account',
  'portal-maya',
  'portal-firm-contact',
] as const

export const MAYA_LANDING_CATALOG_INTENT_IDS = [
  'landing-what',
  'landing-daily',
  'landing-trial',
  'landing-page',
  'landing-portal',
  'landing-pricing',
  'landing-human',
] as const

/** Intents de «outras áreas» — módulos, não campos. */
export const MAYA_CATALOG_INTENT_IDS = [
  'tour',
  'clients',
  'documents',
  'messages',
  'obligations',
  'agenda',
  'fiscal-calendar',
  'irs-campaign',
  'service',
  'alerts',
  'news',
  'billing',
  'settings',
  'human-support',
] as const
