const PERMISSIONS = {
  FIRM_READ: 'FIRM_READ',
  FIRM_CONSULTATIONS_MANAGE: 'FIRM_CONSULTATIONS_MANAGE',

  USERS_READ: 'USERS_READ',
  USERS_CREATE: 'USERS_CREATE',
  USERS_CREATE_ADMIN: 'USERS_CREATE_ADMIN',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_DELETE: 'USERS_DELETE',

  FIRM_CLIENTS_VIEW: 'FIRM_CLIENTS_VIEW',
  FIRM_CLIENTS_MANAGE: 'FIRM_CLIENTS_MANAGE',
  FIRM_ACCOUNTING_SERVICES_VIEW: 'FIRM_ACCOUNTING_SERVICES_VIEW',
  FIRM_ACCOUNTING_SERVICES_MANAGE: 'FIRM_ACCOUNTING_SERVICES_MANAGE',
  FIRM_OBLIGATIONS_MANAGE: 'FIRM_OBLIGATIONS_MANAGE',
  FIRM_DOCUMENTS_MANAGE: 'FIRM_DOCUMENTS_MANAGE',
  FIRM_TASKS_MANAGE: 'FIRM_TASKS_MANAGE',
  FIRM_MESSAGES_MANAGE: 'FIRM_MESSAGES_MANAGE',
  FIRM_BILLING_MANAGE: 'FIRM_BILLING_MANAGE',
  FIRM_SETTINGS_MANAGE: 'FIRM_SETTINGS_MANAGE',
  FIRM_TEAM_MANAGE: 'FIRM_TEAM_MANAGE',
  FIRM_DEPARTMENTS_MANAGE: 'FIRM_DEPARTMENTS_MANAGE',
  FIRM_INVITES_MANAGE: 'FIRM_INVITES_MANAGE',
  FIRM_MEMBER_ROLE_MANAGE: 'FIRM_MEMBER_ROLE_MANAGE',
  FIRM_MEMBER_DEPARTMENT_MANAGE: 'FIRM_MEMBER_DEPARTMENT_MANAGE',
  FIRM_MEMBER_PERMISSION_MANAGE: 'FIRM_MEMBER_PERMISSION_MANAGE',
  FIRM_TEAM_AUDIT_VIEW: 'FIRM_TEAM_AUDIT_VIEW',
  FIRM_REPORTS_VIEW: 'FIRM_REPORTS_VIEW',
};

const FIRM_OPERATIONAL_PERMISSIONS = [
  PERMISSIONS.FIRM_CLIENTS_VIEW,
  PERMISSIONS.FIRM_CLIENTS_MANAGE,
  PERMISSIONS.FIRM_ACCOUNTING_SERVICES_VIEW,
  PERMISSIONS.FIRM_ACCOUNTING_SERVICES_MANAGE,
  PERMISSIONS.FIRM_OBLIGATIONS_MANAGE,
  PERMISSIONS.FIRM_DOCUMENTS_MANAGE,
  PERMISSIONS.FIRM_TASKS_MANAGE,
  PERMISSIONS.FIRM_MESSAGES_MANAGE,
  PERMISSIONS.FIRM_REPORTS_VIEW,
];

const FIRM_OWNER_PERMISSIONS = [
  PERMISSIONS.FIRM_READ,
  PERMISSIONS.FIRM_CONSULTATIONS_MANAGE,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_CREATE_ADMIN,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_DELETE,
  ...FIRM_OPERATIONAL_PERMISSIONS,
  PERMISSIONS.FIRM_BILLING_MANAGE,
  PERMISSIONS.FIRM_SETTINGS_MANAGE,
  PERMISSIONS.FIRM_TEAM_MANAGE,
  PERMISSIONS.FIRM_DEPARTMENTS_MANAGE,
  PERMISSIONS.FIRM_INVITES_MANAGE,
  PERMISSIONS.FIRM_MEMBER_ROLE_MANAGE,
  PERMISSIONS.FIRM_MEMBER_DEPARTMENT_MANAGE,
  PERMISSIONS.FIRM_MEMBER_PERMISSION_MANAGE,
  PERMISSIONS.FIRM_TEAM_AUDIT_VIEW,
];

const FIRM_STAFF_PERMISSIONS = [
  PERMISSIONS.FIRM_READ,
  PERMISSIONS.FIRM_CONSULTATIONS_MANAGE,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_DELETE,
  ...FIRM_OPERATIONAL_PERMISSIONS,
  PERMISSIONS.FIRM_BILLING_MANAGE,
  PERMISSIONS.FIRM_SETTINGS_MANAGE,
  PERMISSIONS.FIRM_TEAM_MANAGE,
  PERMISSIONS.FIRM_DEPARTMENTS_MANAGE,
  PERMISSIONS.FIRM_INVITES_MANAGE,
  PERMISSIONS.FIRM_MEMBER_DEPARTMENT_MANAGE,
];

const ROLE_PERMISSIONS = {
  FIRM_OWNER: FIRM_OWNER_PERMISSIONS,
  FIRM_STAFF: FIRM_STAFF_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.FIRM_REPORTS_VIEW && p !== PERMISSIONS.FIRM_BILLING_MANAGE && p !== PERMISSIONS.USERS_CREATE_ADMIN,
  ),
  CONSULTANT: [
    PERMISSIONS.FIRM_READ,
    PERMISSIONS.FIRM_CONSULTATIONS_MANAGE,
    PERMISSIONS.FIRM_CLIENTS_VIEW,
    PERMISSIONS.FIRM_CLIENTS_MANAGE,
    PERMISSIONS.FIRM_OBLIGATIONS_MANAGE,
    PERMISSIONS.FIRM_DOCUMENTS_MANAGE,
    PERMISSIONS.FIRM_TASKS_MANAGE,
    PERMISSIONS.FIRM_MESSAGES_MANAGE,
    PERMISSIONS.FIRM_ACCOUNTING_SERVICES_VIEW,
    PERMISSIONS.USERS_CREATE,
  ],
  CLIENT: [PERMISSIONS.FIRM_READ, PERMISSIONS.FIRM_CONSULTATIONS_MANAGE],
};

const { normalizeSessionRole } = require('./session-user');

function hasPermission(role, permission) {
  const normalized = normalizeSessionRole(role);
  return (ROLE_PERMISSIONS[normalized] || []).includes(permission);
}

function hasPermissionForUser(user, permission) {
  if (!user) return false;
  if (Array.isArray(user.permissions) && user.permissions.length > 0) {
    return user.permissions.includes(permission);
  }
  if (user.masterAccess) {
    return FIRM_OWNER_PERMISSIONS.includes(permission);
  }
  return hasPermission(user.role, permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasPermissionForUser,
};
